name: Build Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Build project
      run: bun run build
    
    - name: Run tests
      run: bun test
    
    - name: Create standalone binaries
      run: |
        # Create standalone executables for different platforms
        bun build src/cli.ts --compile --target bun-linux-x64 --outfile ai-rewind-linux
        bun build src/cli.ts --compile --target bun-windows-x64 --outfile ai-rewind-windows.exe
        bun build src/cli.ts --compile --target bun-darwin-x64 --outfile ai-rewind-macos
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ai-rewind-linux
          ai-rewind-windows.exe
          ai-rewind-macos
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}