name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        registry-url: 'https://registry.npmjs.org'
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Build project
      run: bun run build
    
    - name: Run tests
      run: bun test
    
    - name: Create standalone binaries
      run: |
        # Create standalone executables for different platforms
        bun build src/cli.ts --compile --target bun-linux-x64 --outfile ai-tracker-linux
        bun build src/cli.ts --compile --target bun-windows-x64 --outfile ai-tracker-windows.exe
        bun build src/cli.ts --compile --target bun-darwin-x64 --outfile ai-tracker-macos
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ai-tracker-linux
          ai-tracker-windows.exe
          ai-tracker-macos
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish to npm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}